version: 2.1
orbs:
  terraform: circleci/terraform@3.2.1
workflows:
  deploy_infrastructure:
    jobs:
      - terraform/fmt:
          checkout: true
          context: terraone
      - terraform/init:
          context: terraone
          requires:
            - terraform/fmt
      - terraform/validate:
          context: terraone
          requires:
            - terraform/fmt
      - terraform/plan:
          context: terraone
          persist-workspace: true
          requires:
            - terraform/validate
      - hold-apply:
          type: approval
          requires:
            - terraform/plan
      - terraform/apply:
          context: terraone
          persist-workspace: true
          requires:
            - hold-apply
      - hold-destroy:
          type: approval
          requires:
            - terraform/apply
      - terraform/destroy:
          context: terraone
          attach-workspace: true
          requires:
            -terraform/apply